# NOTE: Generated By HttpRunner v3.1.6
# FROM: har/test/webportallogin.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseWebportallogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/webportal/login")
            .post("https://dev.1stcs.cn/webportal/login")
            .with_headers(
                **{
                    "Host": "dev.1stcs.cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.59",
                    "accept-encoding": "gzip, deflate, br",
                    "accept": "application/json, text/plain, */*",
                    "Connection": "keep-alive",
                    "Content-Length": "135",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"',
                    "sec-ch-ua-mobile": "?0",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://dev.1stcs.cn",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://dev.1stcs.cn/vue-console/index.html",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "account": "17611617688",
                    "password": "TW1ReVlUY3laakJtT0dZME1HWTNOamRqWlRZMU9EZ3lOV00zWTJObE5HVT0=",
                    "renewal": True,
                    "tenantId": 32,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.ecode", 0)
            .assert_equal("body.reason", "OK")
        ),
    ]


if __name__ == "__main__":
    TestCaseWebportallogin().test_start()
